<!-- Load adapter for old call service function -->
<script type="text/javascript">
	g_adapterWebRoot = "<%=webRoot%>";
</script>
<script type="text/javascript" src="<%=webRoot%>frm/inc/ExtPrototype.js"></script>
<script type="text/javascript" src="<%=webRoot%>frm/inc/Piggy.js"></script>
<script type="text/javascript" src="<%=webRoot%>frm/inc/RemoteHandler.js"></script>

<!-- Load extjs -->
<link rel="stylesheet" type="text/css" href="<%=webRoot%>frm/extjs4/resources/css/ext-all-neptune.css" />
<script type="text/javascript" src="<%=webRoot%>frm/extjs4/ext-all-dev.js"></script>
<script type="text/javascript" src="<%=webRoot%>frm/extjs4/locale/ext-lang-zh_CN.js"></script>

